# TP 9-10 Requêtes opendata et similarité

date de modification 09/04/2026


Objectif : Comprendre les notions de similarité et gestion de vecteurs

# Préparation

**Copier** ce notebook dans votre drive et l'exécuter dans l'environnement colab de google

In [2]:
!pip install -q SPARQLWrapper

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.4/615.4 kB 13.6 MB/s eta 0:00:00

lib pour les embeddings

In [3]:
!pip install -q hnswlib

# embeddings
# !pip install -Uq pymilvus
# !pip install -q pymilvus[model]

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for hnswlib (pyproject.toml) ... done

### Importer le pilote pour accéder aux sources

In [4]:
from SPARQLWrapper import SPARQLWrapper, JSON, CSV
print("pilote importé")

pilote importé

### Manipuler le résultat d'une requête
Fonctions pour afficher le résultat d'une requête

In [5]:
import pandas as pd

#pd.set_option('max_columns', None)
pd.set_option('max_colwidth', None)


# Conversion de JSON vers un dataframe
def get_result(results, limit=100):
  # Get the variable names from the results
  variable_names = results["head"]["vars"]
  # print("variables projetées:", variable_names)

  # Extract tuples using the variable names, taking into account optionnal bindings that may be NULL
  tableau = []
  for result in results["results"]["bindings"][:limit]:
      tableau.append([result.get(var, {}).get("value", "") for var in variable_names])
  return pd.DataFrame(tableau, columns = variable_names)


def query_source(source, requete,  limit=100):
  # invoque le service SPARQL distant
  source.setQuery(requete)

  # formate le résultat en json
  res = source.query().convert()

  # convertit le résultat en un dataframe
  return get_result(res, limit)

print ("fonctions définies")

fonctions définies

### Importer le pilote pour accéder aux sources

In [6]:
from SPARQLWrapper import SPARQLWrapper
print("pilote importé")

pilote importé

## Accès aux sources

Une source est caratérisée par une URL d'accès. Pour éviter une requête transférant trop de données, une source peut ne retourner que les N premiers tuples du résultat d'une requête (N dépend de la source).
Un ensemble de prefixe est défini pour simplifier l'expression des requêtes.

### Accès DBLP

In [7]:
# Set up the SPARQL endpoint
DBLP = SPARQLWrapper("https://sparql.dblp.org/sparql")
DBLP.setReturnFormat(JSON)

DBLP_PREFIX = """
PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
"""

### Accès à la BNF

In [8]:
# Connexion à la BNF
BNF = SPARQLWrapper("https://data.bnf.fr/sparql")
BNF.setReturnFormat(JSON)

BNF_prefix = """
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rda: <http://rdaregistry.info/Elements/w/#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

PREFIX bnf: <http://data.bnf.fr/ontology/bnf-onto/>

PREFIX bio: <http://vocab.org/bio/0.1/>
PREFIX voc2: <http://rdvocab.info/ElementsGr2/>

PREFIX bnfwf: <http://data.bnf.fr/vocabulary/work-form/>

"""
# print(BNF_prefix)

### Accès à DBPEDIA France

In [9]:
# Connexion à DBPEDIA France.
DBPEDIA = SPARQLWrapper("https://fr.dbpedia.org/sparql")
DBPEDIA.setReturnFormat(JSON)

DBPEDIA_prefix =  """
PREFIX dc:   <http://purl.org/dc/terms/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX dbo:  <http://dbpedia.org/ontology/>

# Dans cette source, les noms de propriétés sont en français
PREFIX dbp:  <http://fr.dbpedia.org/property/>
"""
# print(DBPEDIA_prefix)

# Requêtes DBLP

Schéma global

**Author** (authorID, name)

**Publication** (pubID, title, year)

**Publish** (authorID, pubID, venue)

## DBLP1 : liste des auteurs ayant publié à partir de 2024 dans la conférence SIGMOD

In [11]:
requete = DBLP_PREFIX + """
SELECT distinct ?author ?name
WHERE {
  ?publication dblp:authoredBy ?author .
  ?author dblp:creatorName ?name .
  ?publication dblp:title ?title .
  ?publication dblp:publishedIn ?venue .
  ?publication dblp:yearOfPublication ?year
  FILTER (?year >= "2024"^^xsd:gYear && CONTAINS(?venue,"SIGMOD Conference") )
}
# LIMIT 20
"""

# Execute the query and get results
df = query_source(DBLP, requete, limit=1000)
df

                             author               name
0       https://dblp.org/pid/00/232     Alan Halverson
1      https://dblp.org/pid/00/3717   Stefan C. Müller
2    https://dblp.org/pid/00/8454-4         Yujie Wang
3      https://dblp.org/pid/01/24-6          Ling Yang
4      https://dblp.org/pid/01/7213       Mingjie Tang
..                              ...                ...
995    https://dblp.org/pid/67/5612    Mikael Ronström
996    https://dblp.org/pid/67/6944     Tobias Schmidt
997    https://dblp.org/pid/67/9320   Sebastian Hillig
998   https://dblp.org/pid/68/10080          Wenbo Sun
999    https://dblp.org/pid/68/3297  Thibaud Hottelier

[1000 rows x 2 columns]

## DBLP2: les publications d'un auteur donné, postérieures à une date donnée

C'est un requête paramétrée sur l'id d'un auteur

In [ ]:
# J. Leskovec
# AUTHOR = "<https://dblp.org/pid/l/JureLeskovec>"

# I. Trummer
AUTHOR = "<https://dblp.org/pid/85/9079>"

MIN_YEAR = "2000"

requete = DBLP_PREFIX + """
SELECT ?publication ?title ?year ?venue
WHERE {
  BIND( {AUTHOR} as ?author).
  BIND( "{MIN_YEAR}"^^xsd:gYear as ?min_year).

  ?publication dblp:authoredBy ?author .
  ?publication dblp:title ?title .
  ?publication dblp:yearOfPublication ?year .
  ?publication dblp:publishedIn ?venue .
  FILTER (?year >= ?min_year)
}
ORDER BY desc(?year)
LIMIT 100
"""

requete = DBLP_PREFIX + """
SELECT distinct ?venue
WHERE {
  BIND( {AUTHOR} as ?author).
  BIND( "{MIN_YEAR}"^^xsd:gYear as ?min_year).

  ?publication dblp:authoredBy ?author .
  ?publication dblp:title ?title .
  ?publication dblp:yearOfPublication ?year .
  ?publication dblp:publishedIn ?venue .
  FILTER (?year >= ?min_year)
}
ORDER BY desc(?year)
LIMIT 100
"""
requete = requete.replace("{AUTHOR}", AUTHOR)
requete = requete.replace("{MIN_YEAR}", MIN_YEAR)

# Execute the query and get results
query_source(DBLP, requete)

                          venue
0   SIGMOD Conference Companion
1         Proc. ACM Manag. Data
2                           RLJ
3                 Q-DATA@SIGMOD
4                VLDB Workshops
5                          CoRR
6                          AAAI
7     ACM Trans. Database Syst.
8          IEEE Data Eng. Bull.
9                          ICDE
10                         CIDR
11            Proc. VLDB Endow.
12            SIGMOD Conference
13                  Commun. ACM
14                      VLDB J.
15                  SIGMOD Rec.
16    IEEE Trans. Software Eng.
17                         EDBT
18                         ICWS
19                        ICSOC
20                     SERVICES
21                     CloudCom

## DBLP3: les coauteurs d'un auteur donné, triés par nombre de publications communes

In [ ]:
AUTHOR = "<https://dblp.org/pid/00/232>"

MIN_YEAR = "2000"

requete = DBLP_PREFIX + """
SELECT ?coauthor (COUNT(?publication) AS ?numPublications)
WHERE {
  BIND( {AUTHOR} as ?author).
  BIND( "{MIN_YEAR}"^^xsd:gYear as ?min_year).

  ?publication dblp:authoredBy  ?author.
  ?publication dblp:authoredBy ?coauthor .
  ?publication dblp:yearOfPublication ?year .
  FILTER (?author != ?coauthor && ?year >= ?min_year)
}
GROUP BY  ?coauthor
ORDER BY desc(?numPublications)
LIMIT 10
"""
requete = requete.replace("{AUTHOR}", AUTHOR)
requete = requete.replace("{MIN_YEAR}", MIN_YEAR)

# Execute the query and get results
query_source(DBLP, requete)

                                  coauthor numPublications
0          https://dblp.org/pid/d/DJDeWitt               6
1             https://dblp.org/pid/95/4983               4
2           https://dblp.org/pid/p/JMPatel               4
3  https://dblp.org/pid/n/JeffreyFNaughton               4
4            https://dblp.org/pid/51/792-2               3
5             https://dblp.org/pid/33/5504               3
6             https://dblp.org/pid/84/3247               3
7            https://dblp.org/pid/367/4168               2
8            https://dblp.org/pid/367/4148               2
9             https://dblp.org/pid/47/3052               2

## DBLP4: les publications récentes dont le titre contient un certain terme

In [ ]:
TERM = "big data"

requete = DBLP_PREFIX + """
SELECT ?publication ?title ?year ?venue
WHERE {
  ?publication dblp:publishedIn ?venue .
  ?publication dblp:yearOfPublication ?year .
  ?publication dblp:title ?title .
  FILTER (?year >= "2024"^^xsd:gYear && CONTAINS(?title," {TERM} ")  )
}
LIMIT 10
"""

requete = requete.replace("{TERM}", TERM)

# Execute the query and get results
df = query_source(DBLP, requete)
df

,publication,title,year,venue
0,https://dblp.org/rec/conf/acis/ShahNF24,"Explaining the possible negative effects of big data through the interplay between big data analytics, governance, and privacy: A Socio-technical analysis.",2024,ACIS
1,https://dblp.org/rec/conf/ant/RuizSFLMC25,Customer segmentation analysis with big data in health services companies in Colombia: case study.,2025,ANT/EDI40
2,https://dblp.org/rec/conf/bde/LiuHL24,The application of big data to the conservation of wildlife in highland areas.,2024,BDE
3,https://dblp.org/rec/conf/bde/ZhaoZZ24,Behavior detection of mobile phone use at work based on big data and optimized YOLOv6.,2024,BDE
4,https://dblp.org/rec/conf/bdsic/JiangWLML24,Research on fish disease detection based on big data and deep learning.,2024,BDSIC
5,https://dblp.org/rec/conf/bdsic/LiaoY24,DvaDRP: a dual variational autoencoder based on big data for drug response prediction.,2024,BDSIC
6,https://dblp.org/rec/conf/bdsic/ZhangSZHYLCZ25,A fast and parallel framework for massive sensitive data detection based on big data technologies and large language models (LLMs).,2025,BDSIC
7,https://dblp.org/rec/conf/bic/ChenS24,Design of artificial intelligence auxiliary system for elderly care service based on big data analysis.,2024,BIC
8,https://dblp.org/rec/conf/caibda/ZhangC24,"Artificial intelligence, big data and algorithms make it possible for stakeholders to build smart tourism destinations: take Tianzhu Mountain Scenic Area as an example.",2024,CAIBDA
9,https://dblp.org/rec/conf/ciaw/Vysotska24,"Computational intelligence technology for Ukrainian language textual content processing based on big data analysis, NLP and machine learning.",2024,CIAW

# Exercice 1 : requêtes sur DBLP

### a) Associer auteur et publication

A l'aide des requêtes précédentes DBLP1 et DBLP2. Créer une table Publie(authorID, name, title) associant le titre d'une publication avec un auteur, tel que
*   authorID existe dans DBLP1
*   title  existe dans DBLP2

In [1]:
requete2 = DBLP_PREFIX + """
SELECT distinct ?venue
WHERE {
  BIND( {AUTHOR} as ?author).
  BIND( "{MIN_YEAR}"^^xsd:gYear as ?min_year).

  ?publication dblp:authoredBy ?author .
  ?publication dblp:title ?title .
  ?publication dblp:yearOfPublication ?year .
  ?publication dblp:publishedIn ?venue .
  FILTER (?year >= ?min_year)
}
ORDER BY desc(?year)
LIMIT 100
"""

AUTHOR = "<https://dblp.org/pid/85/9079>"
MIN_YEAR = "2000"

requete2 = requete2.replace("{AUTHOR}", AUTHOR)
requete2 = requete2.replace("{MIN_YEAR}", MIN_YEAR)

requete = """
SELECT DISTINCT ?author ?name ?title
WHERE {
  ?publication dblp:authoredBy ?author .
  ?author dblp:creatorName ?name .
  ?publication dblp:title ?title .
  ?publication dblp:publishedIn ?venue .
  ?publication dblp:yearOfPublication ?year .

  FILTER (?year >= "2024"^^xsd:gYear)
  FILTER CONTAINS(?venue, "SIGMOD Conference")
}
ORDER BY ?name
"""



query_source(DBLP, requete)
# Execute the query and get results

resultats = []

requete1 = DBLP_PREFIX + """
SELECT distinct ?author ?name
WHERE {
  ?publication dblp:authoredBy ?author .
  ?author dblp:creatorName ?name .
  ?publication dblp:title ?title .
  ?publication dblp:publishedIn ?venue .
  ?publication dblp:yearOfPublication ?year
  FILTER (?year >= "2024"^^xsd:gYear && CONTAINS(?venue,"SIGMOD Conference") )
}
# LIMIT 20
"""

df1 = query_source(DBLP, requete1)

for _, row in df1.iterrows():
    author = f"<{row['author']}>"
    name = row['name']

    requete2 = DBLP_PREFIX + """
    SELECT ?title
    WHERE {
      BIND( {AUTHOR} as ?author).
      ?publication dblp:authoredBy ?author .
      ?publication dblp:title ?title .
    }
    """

    requete2 = requete2.replace("{AUTHOR}", author)

    df_pub = query_source(DBLP, requete2)

    for _, pub in df_pub.iterrows():
        resultats.append({
            "authorID": author,
            "name": name,
            "title": pub["title"]
        })

NameError: name 'DBLP_PREFIX' is not defined

### b) Co auteurs

En utilisant des requêtes parmi DBLP1 à DBLP4, créer un table **Coauthor**(authorID1, name1, autorID2, name2, nbPubli) telle que les deux auteurs ont au moins une publication commune depuis l'année 2010,  et authorID1 est dans DBLP1.

Indication: proposer 2 solutions:
*   avec DBLP1 et DBLP2
*   avec DBLP1 et DBLP3

# Exercice 2 : Accès par morceau au résultat d'une requête


Un utilisateur veut accéder aux données de manière progressive.

On considère  la requête qui affiche le nom des personnes existant dans dbpedia.

On peut obtenir un certain morceau du résultat d'une requete. Le morceau commençant au tuple i et contenant N tuples est préciser avec les mots-clés `OFFSET i LIMIT N`.

In [ ]:
# import time

# requete = DBPEDIA_prefix + """

# SELECT distinct ?name ?p
# WHERE {
#   ?p rdf:type dbo:Person .
#   ?p foaf:name ?name .
#    FILTER(str(?name) != "")
# }
# offset .... limit .......
# """

# start_time = time.time()
# # exécution de la requête
# df = query_source(DBPEDIA, requete)

# duree = int ( (time.time() - start_time) * 1000)
# print(f"la requête dure {duree} ms")

# df

## Questions
1) Définir une fonction traite_requete_par_bloc(requete) qui retourne un generateur sur une requete de telle sorte que la requete soit lue par morceaux de N tuples et que seuls les morceaux permettant de produire les M lignes demandées par l'utlisateur soit lus. On ne connait pas à l'avance le nombre M de lignes que va lire l'utilisateur. On a M > N.
Indication utiliser le mot clé python `yield` pour retourner un générateur.

In [10]:
requete = DBPEDIA_prefix + """
SELECT distinct ?name ?p
WHERE {
  ?p rdf:type dbo:Person .
  ?p foaf:name ?name
  FILTER(str(?name) != "")
}
"""

# définition d'un générateur
def traite_requete_par_bloc(requete):
  offset = 0
  limit = 5
  while(True):
    custom_requete = requete + f"\nOFFSET {offset} \nLIMIT {limit}"
    df = query_source(DBPEDIA, custom_requete)
    offset += limit

    if df.empty: break

    yield df

# lecture par l'utilisateur
a_lire = 22
lu = 0
for a in traite_requete_par_bloc(requete):
  print(a)
  lu+=1
  if(lu >= a_lire):
    break

print()
if(lu < a_lire):
  print(f"Attention !!!! l'utilisateur n'a obtenu que {lu} lignes sur les {a_lire} à lire")
else:
  print(f"OK, l'utilisateur a obtenu {lu} lignes sur les {a_lire} à lire")

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)>

2) Proposer une solution pour accéder de manière progressive au résultat d'une requête répartie entre 2 sites.

In [ ]:
# à compléter

# Exerice 3 : Cache de requêtes
1) Proposer des améliorations des requêtes précédentes afin d'éviter de poser plusieurs fois une même requête. On suppose que le résultat de la requête ne change pas entre deux invocations de la même requête.

2) Cache avec une capacité limitée : considérer qu'on peut conserver en cache le résultat de C requêtes (C=10) au maximum

In [ ]:
# A compléter

# Exercice 4 : Recherche de publications similaires avec embeddings

On veut exprimer la requête : étant donné une phrase *P*, quelles sont les *k* publications de la source DBLP ayant un titre le plus similaire à *P* et dont l'année > *YEAR_MIN* et publiées dans la conférence *CONFERENCE* ?

Afficher une table (publication, titre, année, distance) avec distance étant la distance cosinus entre une publication et la phrase requête.

Indications:
*    **requêter** la source pour obtenir les publications qui satisfont le critère sur l'année et la conférence.

*   pour chaque publication, inférer un **embedding** de son titre.

*   **indexer** les publications selon leur embedding en utilisant l'index  HNSW : https://zilliz.com/learn/learn-hnswlib-graph-based-library-for-fast-anns

*   Inférer l'embedding de la phrase P.

*   Interroger l'index pour connaître les **k plus proches** embeddings  de l'embedding de la phrase P.

Installer un encodeur pour inférer des embeddings

In [12]:
import numpy as np
from sentence_transformers import SentenceTransformer

# Charger un modèle pré-entraîné (ex: 'all-MiniLM-L6-v2' est rapide et efficace)
model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

 Obtenir les publications tq année >YEAR_MIN et conférence = CONFERENCE

In [23]:
YEAR_MIN = 2023

CONFERENCE="SIGMOD Conference"

requete = DBLP_PREFIX + """
# SELECT  (count(?publication) as ?nb)
# WHERE {

SELECT ?publication ?title ?year
WHERE {
  ?publication dblp:publishedIn ?venue .
  ?publication dblp:yearOfPublication ?year .
  ?publication dblp:title ?title .
  FILTER (?year >= "{YEAR_MIN}"^^xsd:gYear && CONTAINS(?venue,"{CONFERENCE}")  )
}

# }
"""

requete = requete.replace("{YEAR_MIN}", str(YEAR_MIN))
requete = requete.replace("{CONFERENCE}", CONFERENCE)

# Execute the query and get results
publications = query_source(DBLP, requete, limit=1000)
publications

,publication,title,year
0,https://dblp.org/rec/conf/sigmod/0001000TC0X25,Authenticating Multi-Chain Queries: Verifiable Virtual Filesystem Is All You Need.,2025
1,https://dblp.org/rec/conf/sigmod/000123,Mixed Methods Machine Learning.,2023
2,https://dblp.org/rec/conf/sigmod/000123a,DEI Perspectives in Information Technology Education.,2023
3,https://dblp.org/rec/conf/sigmod/0001FDZ24,Beyond Bloom: A Tutorial on Future Feature-Rich Filters.,2024
4,https://dblp.org/rec/conf/sigmod/0001HSV23,Seventh Workshop on Data Management for End-to-End Machine Learning (DEEM).,2023
...,...,...,...
286,https://dblp.org/rec/conf/sigmod/ZhuSA23,Acheron: Persisting Tombstones in LSM Engines.,2023
287,https://dblp.org/rec/conf/sigmod/ZhuSKMMHCTH0KKS25,Rockhopper: A Robust Optimizer for Spark Configuration Tuning in Production Environment.,2025
288,https://dblp.org/rec/conf/sigmod/ZhuTCKAACCCDFGH23,Towards Building Autonomous Data Services on Azure.,2023
289,https://dblp.org/rec/conf/sigmod/ZhuWDZ24,Learned Query Optimizer: What is New and What is Next.,2024
290,https://dblp.org/rec/conf/sigmod/ZimmererDKWOK25,"Pruning in Snowflake: Working Smarter, Not Harder.",2025

pour chaque publication, inférer un **embedding** de son titre.

*   List item
*   List item

In [17]:
# les titres à encoder
titres = np.array(publications['title']).astype(str).tolist()
num_elements = len(titres)
print('nb de titres de publication :', num_elements)

# Inférer les embeddings
embeddings = model.encode(titres, convert_to_numpy=True)
# print('embeddings shape', embeddings.shape)

dim = embeddings.shape[1]
print("dimension d'un embedding:", dim) #384 dimensions par vecteur

# les id des titres dans [0, num_elements[
ids = np.arange(num_elements)

nb de titres de publication : 291
dimension d'un embedding: 384

**indexer** les publication selon leur embedding en utilisant l'index  HNSW

On commencer par créer l'index

In [18]:
import hnswlib

# Declaring index
index = hnswlib.Index(space = 'cosine', dim = dim) # possible options are l2, cosine or ip

# Initializing index - the maximum number of elements should be known beforehand
index.init_index(max_elements = 10000, ef_construction = 25, M = 8)

# Controlling the recall by setting ef:
index.set_ef(10) # ef should always be > k

print("index créé")

index créé

On insère les embeddings dans l'index

In [19]:
index.add_items(embeddings, ids)
print(f'added {len(ids)} elts in the index')

added 291 elts in the index

inférer l'embedding de la phrase requête P

In [45]:
# les requêtes
phrase_requetes= titres[:2]
# phrase_requetes= ["distributed query processing"]

query_vectors = model.encode(phrase_requetes, convert_to_numpy=True)


retrouver dans l'index les *k* titres similaires à P, ainsi que les publications associées

In [46]:
# Query dataset, k - number of the closest elements (returns 2 numpy arrays)
labels, distances = index.knn_query(query_vectors, k = 3)

# print(labels)
for i, (L, D) in enumerate(zip(labels, distances)):
  print("requête:", phrase_requetes[i])
  print("titres similaires:")
  for l, d in zip(L, D):
    # print(titres[l], "distance:", abs(round(d,3)))
    print(tuple(publications.iloc[l]), "distance:", abs(round(d,3)))
  print()

requête: Authenticating Multi-Chain Queries: Verifiable Virtual Filesystem Is All You Need.
titres similaires:
('https://dblp.org/rec/conf/sigmod/0001000TC0X25', 'Authenticating Multi-Chain Queries: Verifiable Virtual Filesystem Is All You Need.', '2025') distance: 0.0
('https://dblp.org/rec/conf/sigmod/DinhOY23', 'First Workshop on Verifiable Database Systems.', '2023') distance: 0.434
('https://dblp.org/rec/conf/sigmod/TianLZTHCY0JZJ24', 'LETUS: A Log-Structured Efficient Trusted Universal BlockChain Storage.', '2024') distance: 0.499

requête: Mixed Methods Machine Learning.
titres similaires:
('https://dblp.org/rec/conf/sigmod/000123', 'Mixed Methods Machine Learning.', '2023') distance: 0.0
('https://dblp.org/rec/conf/sigmod/CongYZ24', 'Machine Learning for Databases: Foundations, Paradigms, and Open problems.', '2024') distance: 0.507
('https://dblp.org/rec/conf/sigmod/Baeza-Yates24', 'The Limitations of Data, Machine Learning and Us.', '2024') distance: 0.591

## Question 1
Amliorer la solution afin de créer un dataframe pour le résultat qui doit être une table (publicationID, titre, année, distance).

In [47]:
rows = []

for i, (L, D) in enumerate(zip(labels, distances)):
    for l, d in zip(L, D):
        rows.append({
            "publicationID": publications.iloc[l]["publication"],
            "titre": publications.iloc[l]["title"],
            "annee": publications.iloc[l]["year"],
            "distance": abs(round(d,3)),
            "query": phrase_requetes[i]
        })

df_result = pd.DataFrame(rows)
display(df_result)

,publicationID,titre,annee,distance,query
0,https://dblp.org/rec/conf/sigmod/0001000TC0X25,Authenticating Multi-Chain Queries: Verifiable Virtual Filesystem Is All You Need.,2025,0.000,Authenticating Multi-Chain Queries: Verifiable Virtual Filesystem Is All You Need.
1,https://dblp.org/rec/conf/sigmod/DinhOY23,First Workshop on Verifiable Database Systems.,2023,0.434,Authenticating Multi-Chain Queries: Verifiable Virtual Filesystem Is All You Need.
2,https://dblp.org/rec/conf/sigmod/TianLZTHCY0JZJ24,LETUS: A Log-Structured Efficient Trusted Universal BlockChain Storage.,2024,0.499,Authenticating Multi-Chain Queries: Verifiable Virtual Filesystem Is All You Need.
3,https://dblp.org/rec/conf/sigmod/000123,Mixed Methods Machine Learning.,2023,0.000,Mixed Methods Machine Learning.
4,https://dblp.org/rec/conf/sigmod/CongYZ24,"Machine Learning for Databases: Foundations, Paradigms, and Open problems.",2024,0.507,Mixed Methods Machine Learning.
5,https://dblp.org/rec/conf/sigmod/Baeza-Yates24,"The Limitations of Data, Machine Learning and Us.",2024,0.591,Mixed Methods Machine Learning.

## Question 2 : persistence des embeddings
On veut conserver les embeddings calculés pour une série de requêtes.

On demande de ne jamais recalculer l'embedding d'un titre pour lequel on a déjà son embedding.

Proposer une solution pour tenir compte de cela. Montrer que votre solution fonctionne pour 2 requêtes consécutives. La 2eme requête contenant des tuples inclus dans le résultat de la 1ere requete.

In [55]:
phrase_requetes= titres[:2]
saved_phrases = {}

def getQueryVector(phrase_requetes):
  toQuery = []

  for phrase in phrase_requetes:
    if phrase not in saved_phrases:
      saved_phrases[phrase] = model.encode([phrase], convert_to_numpy=True)[0]
    else:
      print(f"Cache hit: {phrase}")

    toQuery.append(saved_phrases[phrase])

  return np.vstack(toQuery)

getQueryVector(phrase_requetes)
getQueryVector(phrase_requetes)

Cache hit: Authenticating Multi-Chain Queries: Verifiable Virtual Filesystem Is All You Need.
Cache hit: Mixed Methods Machine Learning.

array([[-6.75615743e-02,  2.64440626e-02, -5.59558384e-02,
        -3.40676717e-02, -6.06937148e-03, -5.27618937e-02,
         1.28388684e-02,  2.79377326e-02,  1.21353054e-02,
         4.10967245e-04,  1.41122350e-02,  2.64657754e-03,
         9.81585607e-02,  7.38769118e-03, -2.00218931e-02,
         1.32125488e-03, -8.81127734e-03,  8.24752301e-02,
         5.85627072e-02,  1.39832748e-02, -7.37126991e-02,
        -2.52825227e-02, -2.88805757e-02,  3.37678343e-02,
        -3.36080790e-02, -4.69700545e-02,  1.72078107e-02,
        -6.71722442e-02, -7.60860071e-02, -5.47771528e-02,
         1.41741401e-02, -2.78295558e-02, -1.11189507e-01,
         5.53778149e-02,  3.69436503e-03,  4.14228905e-03,
         8.13759714e-02, -6.54200315e-02, -1.16100088e-01,
        -9.54620987e-02, -1.46434214e-02,  1.26056047e-02,
        -8.66513625e-02,  2.36185221e-03, -9.69624892e-02,
        -4.81880940e-02,  4.05353270e-02,  3.49942856e-02,
        -1.56201487e-02,  2.24340595e-02, -1.16144400e-02,
        -1.09939128e-02, -5.90890460e-03,  8.34281370e-02,
        -1.01385033e-02, -3.67442481e-02,  2.87681771e-03,
        -2.62857173e-02, -1.69932656e-02, -1.24236187e-02,
         4.90247272e-02,  2.57511996e-02, -3.02571394e-02,
         1.82950068e-02,  6.06115311e-02,  1.24055751e-01,
         8.63906816e-02,  2.51882356e-02,  1.19342972e-02,
        -2.08240021e-02, -1.79362632e-02, -6.21459223e-02,
        -6.68829009e-02,  3.73841524e-02, -1.07770655e-02,
         5.07944562e-02, -1.07824430e-01, -1.31989345e-02,
         1.56682003e-02, -1.76951457e-02, -2.04261634e-02,
         3.65155116e-02, -1.15773268e-02,  9.02473927e-03,
        -2.09702644e-03,  3.08874878e-03, -3.45312469e-02,
        -3.88076971e-03, -6.10507000e-03, -2.40190309e-02,
         5.05891219e-02,  2.42797676e-02,  1.29484641e-03,
        -2.57989541e-02,  7.99602568e-02, -3.48338298e-02,
         6.56669447e-03,  1.67355221e-02,  1.04273401e-01,
         1.29267965e-02, -4.44942601e-02, -6.06519403e-03,
        -3.13186906e-02, -7.61648864e-02,  5.13726659e-02,
         1.15127519e-01,  2.71929819e-02, -6.35040030e-02,
        -3.02034281e-02, -4.25075106e-02, -7.15221539e-02,
        -1.86377764e-02, -3.45335305e-02, -2.90429778e-02,
        -1.20726032e-02,  5.14615141e-02, -9.65163205e-03,
         6.44891113e-02, -5.36921844e-02, -2.69583017e-02,
         4.28223982e-02,  1.34184654e-03,  7.54943639e-02,
        -3.58834788e-02,  7.17318654e-02, -5.12433276e-02,
         9.80534405e-03,  9.12434786e-34, -4.96846065e-02,
         8.29061642e-02,  8.87045786e-02,  5.67152537e-02,
         3.23051885e-02,  1.97384562e-02,  5.55960909e-02,
        -5.94314421e-03, -1.40223294e-01, -7.57034542e-03,
        -1.41062448e-03,  5.80691174e-02,  7.82698859e-03,
        -3.52189094e-02,  1.31226972e-01,  2.28027180e-02,
        -4.48719412e-02, -1.60765350e-02,  1.21704668e-01,
         6.69626892e-02,  2.43556798e-02, -3.92068774e-02,
         1.16100414e-02,  1.02459956e-02,  7.71086812e-02,
        -4.32508737e-02,  1.75775494e-02, -1.31885782e-02,
         6.01238385e-02, -9.78871342e-03, -3.64823565e-02,
        -4.67891693e-02,  3.13902982e-02,  6.80596977e-02,
        -2.60769706e-02,  8.14994797e-02, -2.48215441e-02,
        -3.46672311e-02, -4.29894738e-02, -1.04059003e-01,
         4.27375138e-02, -4.11319584e-02, -2.00827140e-02,
        -3.98928393e-03, -9.97966975e-02,  3.57922465e-02,
        -6.25128895e-02,  3.71001544e-03, -1.86837255e-03,
         2.92048771e-02,  5.82427643e-02,  1.26302261e-02,
        -4.54016328e-02, -6.05971515e-02,  1.60684381e-02,
        -4.23493199e-02, -2.34866925e-02,  6.29196921e-03,
        -1.66333336e-02,  1.00668460e-01, -4.51249555e-02,
        -2.80049518e-02, -2.94820275e-02, -1.79464985e-02,
        -1.04785107e-01, -4.33146246e-02, -3.23524624e-02,
        -9.82091203e-02,  9.31793451e-02,  4.10656780e-02,
        -2.55421940e-02,  1.86995286e-02, -2.86138878e-04,
        -2.94310134e-02, -2.71445476e-02, -2.93667112e-02,
        -6.11189827e-02, -2.29214393e-02,  4.47820053e-02,
         1.35485074e-02, -4.18505259e-02, -8.09286982e-02,
         8.37138854e-03,  1.29098222e-01,  2.88103794e-04,
        -2.48073880e-02, -3.46417986e-02, -5.50506916e-03,
        -4.82661538e-02, -3.70453894e-02,  2.00779829e-02,
         2.34634187e-02,  1.87915370e-01,  3.48823033e-02,
         4.39623976e-03, -1.83990378e-33, -2.52162665e-02,
        -8.86861682e-02,  6.06914870e-02,  7.02551156e-02,
         3.62455994e-02,  4.61608469e-02, -4.45595719e-02,
        -5.14954180e-02, -7.73122609e-02, -3.32288258e-02,
        -1.48384003e-02, -2.93772388e-03,  3.12622078e-02,
        -5.65143824e-02,  9.38600302e-03,  2.31054202e-02,
        -3.28010879e-02, -1.23739235e-01,  3.80631909e-02,
         3.77607495e-02, -1.16641577e-02,  5.62799610e-02,
         3.51216644e-02,  1.34998178e-02,  8.29058886e-02,
         7.73454085e-02, -5.88925369e-02, -1.59197506e-02,
        -3.25394012e-02,  2.44549196e-02, -1.09491646e-02,
        -8.54895115e-02,  9.58086550e-03, -1.71793476e-01,
        -2.33271904e-02, -3.32322009e-02,  5.92303872e-02,
         1.08462125e-01, -5.36098257e-02,  9.67553537e-03,
        -3.67143321e-06, -1.82835665e-02, -7.18204826e-02,
        -8.10405239e-04, -5.50832190e-02, -2.46353373e-02,
        -1.99949723e-02,  5.74260950e-02, -3.32597122e-02,
        -4.94772196e-03, -9.75476205e-03,  8.60518869e-03,
         9.96997282e-02, -3.20427939e-02,  1.69518944e-02,
         5.92617691e-02, -2.15950310e-02,  5.57027459e-02,
         3.77215669e-02,  6.62926510e-02,  1.00947050e-02,
        -1.89036056e-02,  2.30060630e-02,  1.03746273e-01,
         4.36961558e-03, -2.60169096e-02,  2.33239438e-02,
        -3.00845038e-02, -1.13943778e-01,  5.42612299e-02,
         8.39288998e-03,  4.60512005e-04,  1.12596655e-03,
         5.67504019e-02,  1.30555138e-01, -3.70428339e-02,
        -4.06547310e-03, -6.84676021e-02, -1.53743764e-02,
         8.31492618e-02, -2.72498489e-03,  4.25097607e-02,
        -1.52757140e-02,  6.00538291e-02,  6.29922450e-02,
        -7.99167752e-02,  2.02322472e-02, -4.87273820e-02,
         5.86991534e-02,  2.02101823e-02, -3.93403322e-02,
        -2.30225511e-02, -9.08592269e-02, -3.35582308e-02,
         1.76857617e-02, -1.97764951e-08, -2.05470379e-02,
        -3.06896400e-02, -2.73456033e-02, -1.60453860e-02,
         7.92392716e-03,  2.37265974e-03, -3.37860510e-02,
         6.40085936e-02, -5.32086827e-02,  2.69728247e-03,
         8.40012655e-02, -1.85539071e-02, -3.52739915e-02,
        -2.39662118e-02, -4.63134870e-02, -1.24674793e-02,
         4.72978763e-02, -8.75696947e-04, -6.25303388e-02,
         1.10093923e-02, -4.08276357e-02,  9.97835621e-02,
        -2.77580693e-02,  3.78269739e-02,  4.31564823e-03,
         4.86569293e-02,  1.31936684e-01, -5.99182444e-03,
         5.08747734e-02,  7.69336671e-02,  1.71093235e-03,
        -3.38874757e-02,  5.67791797e-03,  3.86456996e-02,
        -8.89781639e-02,  5.18584289e-02, -4.19276655e-02,
         4.19174097e-02, -4.63944972e-02, -4.82117981e-02,
        -2.10747998e-02,  5.50666936e-02, -1.41119314e-02,
         1.96188986e-02,  4.53211032e-02, -5.84516972e-02,
        -1.74884629e-02,  2.30802838e-02, -3.25869094e-03,
         3.28954197e-02, -1.05496189e-02, -4.50638458e-02,
        -1.16937095e-02,  1.37632504e-01,  3.84600312e-02,
        -2.80156713e-02,  8.59798957e-03,  3.86798494e-02,
         1.00598365e-01,  2.15310697e-02,  3.82010639e-02,
        -1.92580801e-02,  3.79302986e-02,  8.20123777e-03],
       [ 1.87400877e-02, -1.78231094e-02,  1.09701239e-01,
        -2.29339791e-03, -1.76760706e-03, -3.16412561e-02,
        -9.17787896e-04, -3.98450196e-02, -8.35872665e-02,
        -8.09080303e-02,  3.28765847e-02, -2.36301646e-02,
        -2.22071446e-02, -3.32524069e-02, -5.52124344e-02,
         1.25351278e-02,  1.38936583e-02, -2.99001690e-02,
        -1.01788849e-01, -5.50573394e-02, -5.31050377e-03,
         6.71750531e-02, -8.13903064e-02, -1.38721969e-02,
        -1.60840787e-02,  5.62916929e-03,  5.93833588e-02,
         6.91773221e-02,  7.38553256e-02, -3.20539549e-02,
         3.34145762e-02,  9.62581635e-02, -4.40994240e-02,
         3.36500816e-02, -7.30863288e-02,  6.84256926e-02,
        -1.00325039e-02,  2.97849439e-02,  3.50667955e-03,
         2.52093412e-02, -8.77463818e-02,  2.45773923e-02,
         4.40459773e-02, -1.09405825e-02,  3.42892818e-02,
        -2.38113198e-02, -3.45726237e-02, -8.36314261e-02,
        -4.53808866e-02,  3.99056002e-02, -3.51387821e-02,
        -1.77746173e-02, -3.42819616e-02, -9.96050518e-03,
        -5.84452925e-03, -4.23341803e-02, -1.86004955e-03,
         1.20073026e-02,  8.69896039e-02, -2.32723597e-02,
        -2.64606234e-02, -3.34866643e-02, -8.94505084e-02,
         6.06278889e-02,  4.27781232e-02, -1.10692959e-02,
        -6.74853250e-02,  6.84618428e-02, -4.37567160e-02,
        -7.70344725e-03, -4.34406549e-02,  4.55303937e-02,
        -8.43900517e-02,  3.62361781e-02,  4.76658950e-03,
         2.42598336e-02,  4.98677604e-02, -2.47764215e-02,
         4.45948280e-02, -4.40819785e-02, -6.47488609e-02,
         4.22032364e-03, -6.44038096e-02,  1.84282742e-03,
         1.10164493e-01,  2.20449753e-02, -5.77999093e-02,
         3.39617953e-03, -7.35585168e-02, -1.91923752e-02,
        -2.71724854e-02,  7.23282024e-02,  5.43958507e-02,
        -8.04961324e-02, -6.58639818e-02,  1.69892423e-03,
        -9.39598307e-04, -1.07024625e-01,  5.09433076e-02,
         1.10664174e-01, -7.30751902e-02,  6.10917732e-02,
        -5.55778928e-02, -1.29634216e-02, -4.50788252e-02,
        -7.17775524e-02,  5.48783913e-02, -6.66901935e-03,
         8.18074197e-02, -6.77032471e-02, -7.11590946e-02,
         6.79731220e-02, -5.34882098e-02, -1.34762311e-02,
         2.36102697e-02, -6.15198947e-02,  4.40367609e-02,
        -2.98920944e-02,  6.30924180e-02,  6.63718432e-02,
        -2.52841935e-02,  3.15944897e-03,  8.13475102e-02,
        -1.33832029e-04,  9.09348857e-03,  7.64112845e-02,
        -4.37407047e-02, -2.72321431e-33,  1.48015162e-02,
        -9.99657530e-03,  2.62622070e-02,  7.47125968e-02,
         4.65506464e-02, -3.64681035e-02, -8.32809731e-02,
        -5.41233942e-02,  1.89230144e-02,  3.83628532e-02,
         4.52498235e-02,  4.90214638e-02, -1.79407913e-02,
         1.38596743e-02,  1.10299855e-01,  3.94393392e-02,
        -3.89518659e-03,  7.02391863e-02, -8.48726407e-02,
         3.71386409e-02, -7.37126730e-03, -7.79175945e-03,
         6.71018958e-02,  3.28442603e-02, -4.82365042e-02,
        -2.87414324e-02,  4.29033488e-02,  1.99810192e-02,
        -1.37636773e-02,  3.36080529e-02, -4.36075777e-02,
         4.27146303e-03, -1.07210368e-01,  6.47560209e-02,
        -2.27558631e-02,  1.60847530e-02,  4.52264249e-02,
         3.51252453e-03,  2.48280208e-04,  1.67531930e-02,
        -6.82262927e-02, -6.44523725e-02,  7.65047967e-02,
        -7.26022720e-02,  1.29536958e-02,  7.58505762e-02,
         1.07392883e-02, -6.76178783e-02,  3.01962420e-02,
         4.56062779e-02, -2.09200252e-02, -2.38213222e-02,
         3.72258797e-02, -5.10672592e-02, -4.29807790e-02,
         7.12978244e-02, -4.99569252e-02,  1.89611334e-02,
         1.52367363e-02,  6.27230480e-03,  4.43495018e-03,
        -3.76242511e-02, -5.63365035e-02, -4.14753109e-02,
        -1.30357472e-02,  2.97880955e-02, -1.93248980e-03,
        -4.05261070e-02,  5.51222116e-02, -4.07209583e-02,
         8.58768634e-03,  7.90277589e-03,  6.14444949e-02,
        -3.65035725e-03,  8.76253238e-04, -1.83414202e-02,
         1.21106720e-03,  5.10226786e-02,  1.37811443e-02,
        -3.06379963e-02,  1.56876328e-03,  4.15090770e-02,
        -3.55714485e-02, -9.51500759e-02, -2.94361915e-02,
        -1.33714238e-02, -2.18839757e-02, -2.65935864e-02,
        -1.21695988e-01,  1.38816033e-02, -1.29234001e-01,
         2.42053997e-02,  4.09566052e-02,  5.94160371e-02,
        -4.13294099e-02, -2.34987841e-34, -1.19017214e-01,
         3.74751166e-02,  1.07206153e-02,  6.87718168e-02,
         4.71317992e-02,  1.96441598e-02, -2.53565870e-02,
        -6.37299195e-02,  9.79395732e-02,  1.94796547e-02,
         5.14927506e-02,  8.16871319e-03, -3.54876295e-02,
        -4.35834285e-03,  3.75112239e-03,  3.12872790e-02,
         1.38653899e-02,  1.25133386e-02,  7.02701807e-02,
         8.56784508e-02,  2.87012383e-02,  3.94229181e-02,
        -1.33125018e-03,  1.64955761e-03,  3.08618490e-02,
        -4.32272023e-03, -4.27267216e-02,  5.65628596e-02,
        -8.84436164e-03, -5.20726219e-02,  6.58371532e-03,
        -7.12488741e-02, -2.14393325e-02, -1.69624370e-02,
        -2.42224298e-02,  2.85962168e-02,  6.16690982e-03,
        -4.06610640e-03,  3.48239318e-02,  1.09203905e-01,
         5.03902249e-02,  7.73615390e-02, -1.36983708e-01,
         2.23029330e-02,  3.13115120e-02, -3.93394977e-02,
        -6.08189404e-02, -7.33113661e-02,  3.66427265e-02,
        -1.40580591e-02, -2.45771408e-02,  1.28860082e-02,
        -7.64539391e-02, -1.12488987e-02,  4.55692876e-03,
        -2.85119265e-02,  5.49528301e-02, -6.40161633e-02,
        -1.92381851e-02,  6.47012666e-02, -1.24813378e-01,
        -3.73777151e-02, -3.51276807e-02,  6.06101714e-02,
         1.54860262e-02, -1.34479795e-02, -2.97472172e-04,
        -4.31054942e-02, -8.06036144e-02,  9.01099760e-03,
         2.10213847e-02,  1.36222132e-02,  3.03413440e-02,
        -2.12440211e-02,  1.35905407e-02, -8.38487148e-02,
        -2.68961992e-02,  1.08396048e-02, -3.26426625e-02,
        -8.55955575e-03,  3.70017663e-02, -1.11919560e-01,
         7.03788772e-02,  2.77782846e-02,  2.20560189e-02,
         8.41384754e-02, -4.05588113e-02, -2.18792278e-02,
         6.56214803e-02, -1.03754185e-01, -5.04423194e-02,
         3.82547714e-02,  4.98935804e-02,  1.15793962e-02,
        -8.27040970e-02, -1.40291281e-08,  7.35844150e-02,
        -8.80859718e-02,  5.79966567e-02,  1.84624922e-02,
         4.23655808e-02,  9.43422392e-02, -1.36552587e-01,
         4.43966761e-02, -3.48101929e-02,  1.79599430e-02,
         3.50444287e-04,  1.00277213e-03, -4.06974480e-02,
        -1.38892501e-03, -2.39181947e-02,  1.23172402e-02,
         6.82469876e-03,  7.92847872e-02, -2.44558174e-02,
         3.75510007e-02,  7.20011666e-02,  7.57964402e-02,
         5.10955555e-03, -2.37461515e-02,  6.02175146e-02,
        -4.93699089e-02, -2.11903583e-02,  6.06093146e-02,
         3.86988930e-02,  8.98972303e-02, -2.33891923e-02,
         9.00191739e-02, -4.66429256e-02,  5.75282350e-02,
         4.45043258e-02,  2.71407180e-02,  5.09383157e-02,
        -2.13743001e-02, -6.68887496e-02,  1.08575359e-01,
        -4.21382487e-02,  4.55426201e-02, -6.09691218e-02,
        -6.44040704e-02,  1.04660235e-01,  4.65917923e-02,
         4.10471484e-02, -1.08435310e-01,  6.35932833e-02,
         7.30444193e-02,  2.25952398e-02,  3.94024327e-02,
         4.63637263e-02,  7.27944523e-02,  5.12516946e-02,
        -1.10231042e-02,  3.86927910e-02, -5.81871755e-02,
         3.88568937e-04, -3.50785851e-02,  3.50797921e-02,
        -1.42218650e-03, -7.46161267e-02,  5.61485961e-02]], dtype=float32)

## Question 3 : recherche k-NN exhaustive

Soit V un tableau de vecteurs, p un vecteur requête et k un entier.

a) Ecrire une fonction NN(V, p, k) qui effectue la recherhe exhaustive des k NN de p parmi les V vecteurs.

Indication : comparer p avec **tous** les vecteurs de V.

b) Montrer que k-NN est plus lent que l'accès par index pour un ensemble V suffisamment grand. Vous pouvez générer V aléatoirement dans cette question.

c) Mettre en évidence l'aspect approximatif de la recherche ANN : montrer un cas où le résultat k-ANN ne contient pas tous les voisins k-NN.

In [ ]:
import sklearn
from sklearn.metrics.pairwise import cosine_distances


def cosine_distance(p, V):
  p_mat = p.reshape(1, -1)
  return cosine_distances(p_mat, V)[0]

# Exemple k-NN (exhaustif)

d = cosine_distance(..................   ..............)
indices_tries = ............

# Exercice 5 : Requête hybride avec embeddings  et SQL

DuckDB est tres efficace pour gérer des relations
mais ne manipule pas de données vectorielles et ne propose pas de recherche ANN (cf. cours 10).

On considère la table :

**Publication** (publicationID, year, venue, title)


On veut combiner une recherche ANN avec des requêtes SQL de sélection sur des données gérées dans DuckDB.

Soit la requête **R1** :

SELECT *, distance(p.title, "phrase recherchee") as distance

FROM Publications p

WHERE (year between 2022 and 2024) and venue like '%VLDB'

ORDER BY distance

LIMIT 10

La fonction distance(phrase1, phrase2) renvoie la distance cosinus entre les embeddings (vecteurs) de deux phrases.

## Preparation

In [ ]:
!pip install -q duckdb

In [ ]:
!pip install -q itables

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 18.7 MB/s eta 0:00:00

In [ ]:
# pour améliorer l'affichage des tableaux contenant le resultat d'une requete
from itables import init_notebook_mode
init_notebook_mode(all_interactive=True)

La fonction **display** affiche les n premières lignes du résultat d'une requête

In [ ]:
def display(query, n=30):
    return query.limit(n).df()

In [ ]:
import duckdb

# option 1: la base créée sera persistente dans un fichier
# db = duckdb.connect('mabase')

# option 2: la base sera uniquement en mémoire. Elle sera supprimée en fin de session.
db = duckdb.connect(':memory:')

# vérifier que le service fonctionne en posant une première requête.
r = db.sql("SELECT 'hello' as col ")
display(r)

     col
0  hello

In [ ]:
def display_schema(table):
  return display(db.sql(f"""
    SELECT column_name, data_type
    FROM duckdb_columns
    WHERE table_name = '{table}'
  """))

# def display_all_views():
#   return display(db.sql("select view_name, sql, temporary from duckdb_views"))


def function_exists(name):
  existing_functions = db.sql("select distinct function_name, from duckdb_functions() WHERE function_type = 'scalar' ").df()
  return name in existing_functions.values

## Créer la table des Publications

Obtenir des données (exple des publication DBLP)

In [ ]:
grande_requete = DBLP_PREFIX + """
SELECT ?publication ?year ?venue ?title
WHERE {
  ?publication dblp:publishedIn ?venue .
  ?publication dblp:yearOfPublication ?year .
  ?publication dblp:title ?title .
  FILTER (    ?year >= "2010"^^xsd:gYear
           && ( CONTAINS(?venue,"SIGMOD")
                || CONTAINS(?venue,"VLDB")
                || CONTAINS(?venue,"EDBT")
                || CONTAINS(?venue,"ICDE")
              )
          )
}
ORDER BY desc(?year) ?title
LIMIT 1000
"""

# Executer la requete en plusieurs appels

# lire 1000 pulications par appel
MAX_RESULT = 1000

publications = query_source(DBLP, grande_requete, limit=MAX_RESULT)

# lire 3000 de publications au total
for i in range(1, 3):
  suite = query_source(DBLP, grande_requete + f" OFFSET {MAX_RESULT*i}", limit=MAX_RESULT)
  publications = pd.concat([publications, suite])

print("nombre de publications", len(publications))
publications

nombre de publications 3000

                                           publication  year  \
0           https://dblp.org/rec/conf/edbt/ArnoldSZK26  2026
1            https://dblp.org/rec/conf/edbt/Dittrich26  2026
2     https://dblp.org/rec/conf/edbt/FujiwaraGMIKNNK26  2026
3             https://dblp.org/rec/conf/edbt/MaWWLZQ26  2026
4            https://dblp.org/rec/conf/edbt/AslamKSK26  2026
..                                                 ...   ...
995  https://dblp.org/rec/journals/pvldb/LeiLZZYXXWD24  2024
996        https://dblp.org/rec/journals/pvldb/FanLZ24  2024
997            https://dblp.org/rec/conf/edbt/AppelW24  2024
998            https://dblp.org/rec/conf/vldb/AppelW24  2024
999        https://dblp.org/rec/journals/vldb/UstaKU24  2024

                   venue  \
0                   EDBT
1                   EDBT
2                   EDBT
3                   EDBT
4                   EDBT
..                   ...
995    Proc. VLDB Endow.
996    Proc. VLDB Endow.
997  EDBT/ICDT Workshops
998       VLDB Workshops
999              VLDB J.

                                                                                                       title
0                          A Declarative, Recursive SQL Framework for Composable Machine Learning Ensembles.
1                                                A Functional Data Model and Query Language is All You Need.
2                                     Accelerating Graph Construction for MIPS without Search Accuracy Loss.
3                                                        Accelerating K-Core Computation in Temporal Graphs.
4                                                    Adaptive Query-Aware Hybrid Search in Vector Databases.
..                                                                                                       ...
995                                  X-Stor: A Cloud-native NoSQL Database Service with Multi-model Support.
996                                                    X-TED: Massive Parallelization of Tree Edit Distance.
997                             XCrowd: A Realistic Crowd Simulation Tool for Efficient Movement Management.
998                                   XCrowd: Real-Time Dynamic Crowd Movement Simulation on Graph Networks.
999  xDBTagger: explainable natural language interface to databases using keyword mappings and schema graph.

[3000 rows x 4 columns]

Insérer les publications dans DuckDB

In [ ]:

# # Ajouter un numéro de publication pubID allant de 0 à n
# if 'pubID' not in publications.columns:
#   ...............

# # type int pour l'attribut year
# publications['year'] = publications['year'].astype(int)


# # importer les données dans une table DuckDB
# db.sql("drop table if exists publications")
# db.from_df(................).create(................)


# # on supopse que les publications ne sont plus dans l'application mais seulement dans DuckDB
# # del publications

# res = db.sql("SELECT * FROM publications ORDER BY pubID")
# display(res,5)

In [ ]:
display_schema('publications')

Empty DataFrame
Columns: [column_name, data_type]
Index: []

## Question 1: Indexation

Exporter les titres de la table publication, triés par pubID

In [ ]:
# titres_df = db.sql("SELECT ................").df()
# titres_publi = np.array(.................))

obtenir les embeddings de ces titres

In [ ]:
# Inférer les embeddings
import time
debut = time.time()
all_embeddings =.................
duree = time.time() - debut
print(f"Durée d'exécution : {duree:.3f} secondes, pour {len(titres_publi)} titres de publication")
# print('embeddings shape', embeddings.shape)

SyntaxError: invalid syntax (1819695403.py, line 4)

Indexer les embeddings

## Question 2 : Traiter la requête R1

Définir la fonction `requête_hybride1` qui traiter R1 en effectuant le maximum de traitements dans la base SQL.

Indication :  commencer par rechercher les K-ANN puis appliquer la condition de sélection

In [ ]:
def requête_hybride1(condition_selection, phrase):



  return res.df()

# Exemple
requête_hybride1("(year between 2020 and 2024) and venue like '%VLDB%'", "distributed query processing")

## Question 3: Fonction UDF

Définir une fonction UDF distance(p1,p2) retournant la distance cosinus entre les 2 vecteurs associées aux phrases p1 et p2

Proposer une solution pour traiter R1 en invoquant la fonction distance.

In [ ]:
# Exemple d'UDF

from duckdb.typing import FLOAT, VARCHAR

# Définition d'une UDF en Python
def carre(x):
    return x * x

# Enregistrement de l'UDF dans DuckDB
function_name = 'carre_UDF'
if function_exists(function_name):
  db.remove_function(function_name)
db.create_function(function_name, carre, [FLOAT], FLOAT)

print('UDF définie: ', function_name)

db.sql(f"SELECT carre_UDF(3)").df()

# FAQ: Questions diverses

## Mise au point des requêtes
Pour débugguer et **mettre au point vos requêtes** SPARQL, il est utile de les tester directement sur l'interface du point d'accès dédié de la source de données. L'avantage est que cela vous retourne un message indiquant plus précisément la nature et l'endroit où se trouve l'erreur dans la requête.

*   [DBLP](https://sparql.dblp.org/) et un [tuto](https://github.com/dblp/kg/wiki/dblp-KG-Tutorial)

*   [BNF](http://data.bnf.fr/sparql) voir des [exemples](https://api.bnf.fr/sparql-endpoint-de-databnffr)

*   [DBPedia](http://fr.dbpedia.org/sparql) et la liste de tous les [prefixes](http://fr.dbpedia.org/sparql?nsdecl)

## Autres sources de données
Autres sources à votre disposition pour proposer des requêtes multi-sources:

1.   [Mondial](http://www.semwebtech.org/mondial/10/sparql) : données géopolitiques. Attention le résulat des requêtes est en XML pas en JSON.
2.   [Persée](data.persee.fr) : données bibliographiques alignées avec plusieurs autres sources dont dbpedia. Voir des [exemples](http://data.persee.fr/ressources/requetes-exemples/)
3.   [BioPortal](http://sparql.bioontology.org)
4.    [IdRef](https://data.idref.fr/sparql) serveur d’autorité IdRef et les références bibliographiques en provenance du Sudoc.
5.   [Insee](https://rdf.insee.fr/sparql)
6.  [Geonames web services](https://www.geonames.org/export/ws-overview.html)

## SPARKLIS : aide à l'écriture de requêtes Sparql
Pour exprimer vos requêtes en *langage naturel* et les traduire automatiquement en SPARQL, voir l'appli [Sparklis](http://www.irisa.fr/LIS/ferre/sparklis/)


*   onglet **Sparklis** pour exprimer vos requêtes en langage naturel
*   onglet **YASGUI** pour voir la traduction en Sparql

## Nombre d'éléments dans le resultat d'une requête
Pour compter le nombre d'éléments d'une requête, utiliser la notation avec requête imbriquée dans le where :

SELECT (count(1) as ?nb)

WHERE { *sous-requete* }